"""Custom exceptions for ArogyaMitra AI."""
from backend.exceptions.arogya_errors import (
    ArogyaError,
    InvalidRecordTypeError,
    FutureDateError,
    FileSizeLimitError,
    UnsupportedFileTypeError,
    OCRExtractionError,
    InvalidParameterValueError,
    MissingUnitError,
    EmptyReminderTitleError,
    InvalidDueDateError,
    InvalidRecurrenceError,
    ShareTokenExpiredError,
    InvalidShareTokenError,
    InsufficientDataError,
    RecordNotFoundError,
    PromptInjectionDetectedError,
    AuthenticationError,
    AuthorizationError,
    DatabaseError,
    RecordAlreadyExistsError,
)

__all__ = [
    "ArogyaError",
    "InvalidRecordTypeError",
    "FutureDateError",
    "FileSizeLimitError",
    "UnsupportedFileTypeError",
    "OCRExtractionError",
    "InvalidParameterValueError",
    "MissingUnitError",
    "EmptyReminderTitleError",
    "InvalidDueDateError",
    "InvalidRecurrenceError",
    "ShareTokenExpiredError",
    "InvalidShareTokenError",
    "InsufficientDataError",
    "RecordNotFoundError",
    "PromptInjectionDetectedError",
    "AuthenticationError",
    "AuthorizationError",
    "DatabaseError",
    "RecordAlreadyExistsError",
]
